# Name and version of Server Os 
name: Server OS
versin: 0.0.2

# Port Server Os
port: 8000

# List of repositories that will be downloaded and included in the project
repos:
  - https://github.com/Blade-Space/api-wwf
  - https://github.com/Blade-Space/api-wwd
  - https://github.com/Blade-Space/api-wwz

# If you want to connect frontend to server os, set include true and set url of the repository
front-end: 
  include: true
  repo: https://github.com/Blade-Space/front-end